#!/bin/bash

## Check if legacy CSS files have been generated

# Redirect output to stderr.
exec 1>&2

GIT_ROOT=`git rev-parse --show-toplevel`

echo "# Checking all legacy CSS files have been generated..."

if [ ! -d "$GIT_ROOT" ];
then
    echo "# ERROR: cannot detect project path"
fi

export ERROR=0
for FILE in $(git diff --cached --name-only | sed -n '/\.css$/p');
do
    LOCAL_ERROR=0
    LEGACY_CSS_FILE=`echo $FILE | sed 's/\.css//g'`
    LEGACY_CSS_FILE="${LEGACY_CSS_FILE}.css.js"
    if [ ! -f ${LEGACY_CSS_FILE} ]
    then
        echo "# ERROR: legacy CSS ${LEGACY_CSS_FILE} not found, generate it with:"
        ERROR=1
        LOCAL_ERROR=1
    fi
    TEMP_FILE=$(mktemp)
    (cd ${GIT_ROOT} && tools/cssToJavascriptStyle.sh ${FILE} > ${TEMP_FILE})
    diff ${LEGACY_CSS_FILE} ${TEMP_FILE} > /dev/null
    if [ $? -ne 0 ]
    then
        ERROR=1
        LOCAL_ERROR=1
        echo "# ERROR: legacy CSS ${LEGACY_CSS_FILE} is outdated, generate it with:"
    fi
    rm ${TEMP_FILE}
    if [ $LOCAL_ERROR -eq 1 ]
    then
        echo "tools/cssToJavascriptStyle.js ${FILE} > ${LEGACY_CSS_FILE}"
    fi
done

if [ $ERROR -eq 0 ]
then
    echo "# All legacy CSS files seem OK."
fi

exit 1
exit $ERROR
